blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.allBlogs, name='allBlogs'),
    path('<str:slug>/', views.detail, name='blog_detail'),
]

memberships/urls.py
from django.urls import path
from . import views

app_name = 'memberships'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('settings/', views.settings, name='settings'),
    path('success/', views.payment_success, name='payment_success'),
    path('updatesuccess', views.update_success, name='update_success'),
    path('webhook/', views.my_webhook, name='my_webhook'),
    path('join/', views.join, name='join'),
    path('cancel/', views.cancel_subscription, name='cancel_subscription'),

]

readingTeacherOnline/urls.py
from django.contrib import admin
from django.urls import path, include
from courses_site import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('signup/', views.signupuser, name='signupuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('login/', views.loginuser, name='loginuser'),
    path('blog/', include('blog.urls')),
    path('courses/', views.all_courses, name='all_courses'),
    path('courses/<str:slug>/', views.course_detail, name='course_detail'),
    path('courses/<str:slug>/<int:order_number>', views.course_video, name='course_video'),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('memberships/', include('memberships.urls')),
    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="auth/password_reset.html", email_template_name='password_reset_email.html'),
         name="reset_password"),
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="auth/password_reset_sent.html"),
         name="password_reset_done"),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='auth/password_reset_confirm.html'),
         name="password_reset_confirm"),
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='auth/password_reset_done.html'),
         name="password_reset_complete"),
    path('change_password/',
         auth_views.PasswordChangeView.as_view(template_name='auth/change_password.html'),
         name='change_password'),
    path('activation_email_sent', views.activation_email_sent, name='activation_email_sent'),
    path('account_activated', views.account_activated, name='account_activation_complete'),
    path('activate/<uidb64>/<token>/', views.activate_account, name='activate'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'courses_site.views.error_404'

templates/course_site/all_courses.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1 class="p-5">Courses</h1>
        {% for course in courses %}
            {% if course.status == 1 %}
            <a href="{{ course.get_absolute_url }}" class="text-decoration-none text-dark">
            <div class="border m-3 p-3">
                <h3>{{ course.title }}</h3>
                <p>{{ course.description|truncatechars:200 }}</p>
            </div>
            </a>
            {% else %}
                {% if user.is_superuser %}
                    <a href="{{ course.get_absolute_url }}" class="text-decoration-none text-dark">
                    <div class="border m-3 p-3">
                        <h3>{{ course.title }}</h3>
                        <p>{{ course.description|truncatechars:200 }}</p>
                    </div>
                    </a>
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>

{% endblock %}

templates/course_site/course_detail.html
{% extends 'base.html' %}

{% block content %}
    <style>

        .video-length {
            display: flex;
            justify-content: end;
            align-items: center;
            flex-wrap: wrap;
            margin: 0;
        }

    </style>

    <div class="container">
        <h1 class="my-5 pb-3 border-bottom">{{ course_detail.title }}</h1>
        <div class="row justify-content-center">
            <div class="col-12 p-3">
                <h5 class="pt-2 font-weight-bold">Course Description</h5>
                <p>{{ course_detail.description }}</p>
                <div class="row border-bottom justify-content-center">
                    <div class="col-6">
                        <b>Number of Lessons:</b>
                    </div>
                    <div class="col-6 d-flex justify-content-end">
                        {{ number_of_lectures }}
                    </div>
                </div>
                <div class="row border-bottom justify-content-center my-4">
                    <div class="col-6">
                        <b>Course Duration:</b>
                    </div>
                    <div class="col-6 d-flex justify-content-end">
                        <p class="m-0 text-right">{{ total_duration }}</p>
                    </div>
                </div>
                {% if video.activity_pdf %}
                    <div class="row border-bottom justify-content-center">
                        <div class="col-sm-6 col-12">
                            <b>Lesson Resource:</b>
                        </div>
                        <div class="col-sm-6 col-12 d-flex py-2 py-sm-0 justify-content-sm-start justify-content-md-end">
                            <a href="{{ video.activity_pdf.url }}">
                                {{ video.activity_pdf }}
                            </a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="col-12  py-3">
            <div class="list-group">
                {% for video in videos %}
                    <a class="list-group-item list-group-item-action py-0 hover-color" href="{% url 'course_video' slug forloop.counter %}">
                        <div class="row py-2">
                            <div class="col-6">
                                <p class="video-title">{{ video.title }}</p>
                            </div>
                            <div class="col-6">
                                <p class="video-length">{{ video.length_formatter}}</p>
                            </div>
                        </div>
                    </a>
                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}

templates/course_site/loginuser.html
{% extends "base.html" %}

{% block content %}

	<div class="row justify-content-center pt-5">
		<div class="col-3">
			<div class="row justify-content-center my-2">
				<p class="h1">Login</p>
            </div>
            <div class="row justify-content-center my-2">
                <p class="alert-danger">{{ error }}</p>
            </div>

				<form method="POST">
					{% csrf_token %}
					{{ form.as_p }}
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value="{{ request.GET.next }}">
                    {% endif %}
                    <div class="row justify-content-center my-2 align-items-baseline">
{#                        <label class="mx-2"  for="username">Username:</label>#}
                        <input type="text" name="username" autocomplete="current-username" required id="username" placeholder="Username">
                    </div>

                    <div class="row justify-content-center my-2 align-items-baseline">
{#                        <label class="mx-2" for="password">Password:</label>#}
                        <input type="password" name="password" autocomplete="current-password" required id="password" placeholder="Password">
                    </div>
                    <div class="row justify-content-center my-2">
                        <button class="btn btn-primary" type="submit">
                            Login
                        </button>
                    </div>
				</form>
                <div class="row justify-content-center my-2">
                    {% if request.GET.next %}
                        <small>Don't have an account?<a href="{% url 'signupuser' %}?next={{ request.GET.next }}">Sign up here</a></small>
                    {% else %}
                        <small>Don't have an account?<a href="{% url 'signupuser' %}"> Sign up here</a></small>
                    {% endif %}
                </div>
                <div class="row justify-content-center">
                    <small>Forgot password?<a href="{% url 'reset_password' %}"> Reset Password</a></small>
                </div>

			</div>
		</div>





{% endblock %}

templates/course_site/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'lightgallery/dist/css/lightgallery.css' %}">

    <style>
        .background_image {
            background-image: url({% static 'courses_site/group-school-kids-reading-education-min.jpg' %});
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center;
            height: 800px ;
            box-shadow: 0 4px 14px rgba(71, 76, 85, .30);

        }

        .main_heading {
            font-family: Roboto, sans-serif;
            font-weight: 700;
        }

        .img-shadow {
            box-shadow: 0 4px 14px rgba(71, 76, 85, .30);
        }

        {#.video-card {#}
        {#    box-shadow: 0 4px 14px rgba(71, 76, 85, .30);#}
        {#    max-width: 500px;#}
        {#}#}

        .video-container{
            position: relative;
            overflow: hidden;
        }

        .video-container img {
            width: 100%;
            transition: 0.3s all ease-in-out;
        }

        .video-container:hover img{
            transform: scale(1.05);
        }

        .video-container svg {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%);
            fill: dimgrey;
            width: 100px;
        }

        .st0 {
            opacity:0.4;
            fill:#010101;
            enable-background: new;
        }

        .st1 {
            fill:#FFFFFF;
        }

        {#lightgallery background colour#}
        .lg-backdrop {
            background-color: rgba(0,0,0,0.75);
        }

        @media screen and (min-width:992px){
            .row-margin {
            margin: 100px 0 50px 0;
            }
        }

        .container-svg-bg {
            position: relative;
        }

        .background-svg {
            position: absolute;
            transform: translateY(-45px);
            height: 100%;
            width: 100vw;
        }


        .background-svg path {
            fill: #0c9b8d30;
        }



    </style>

    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'lightgallery/dist/js/lightgallery.min.js' %}"></script>
    <script src="{% static 'lg-video/dist/lg-video.min.js' %}"></script>

    <div class="background_image">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-8-sm col-12">
                <div class="row justify-content-center py-5">
                    <div class="col-lg-8 col-9">
                        <h2 class="text-center text-light main_heading d-sm-none ">Comprehensive Courses To Help Your Child Succeed At Reading</h2>
                        <h1 class="text-center text-light main_heading d-none d-sm-block">Comprehensive Courses To Help Your Child Succeed At Reading</h1>
                    </div>
                </div>
                <div class="row justify-content-between">
                    <div class="col m-1 d-flex justify-content-end">
                        <a href="#" class="btn btn-light"><b>Learn More</b></a>
                    </div>
                    <div class="col m-1 d-flex justify-content-start">
                        <a href="{% url 'memberships:join' %}" class="btn btn-light"><b>Get Access</b></a>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="container-svg-bg">
        <svg class="background-svg" preserveAspectRatio="none" aria-hidden="true" viewBox="0 0 1366 700">
            <path d="M1366 614.626V42.2878C1216.44 32.481 1071.16 25.6274 902.892 20.0618C647.674 11.6203 291.457 3.37253 0 0.135254V612.111C313.572 631.987 694.403 637.367 1189.78 619.86C1248.63 617.783 1307.48 616.071 1366 614.626Z"></path>
        </svg>
    <div class="container my-5">



        <div class="row row-margin justify-content-center align-items-center">
            <div class="col-lg-6 col-xs-12">

                    <div id="video-gallery">
                        <a href="https://www.youtube.com/watch?v=lWNwm_qBZ4c">
                            <div class="video-container img-shadow img-fluid">
                                <img class="rounded" src="{% static 'courses_site/youCanTeachYourChildScreenshot.png' %}" alt="youCanTeachYourChildScreenshot.png">
                                    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="-307.4 338.8 91.8 91.8" style="enable-background:new -307.4 338.8 91.8 91.8;" xml:space="preserve">
                                    <g>
                                        <circle class="st0" cx="-261.5" cy="384.7" r="45.9"/>
                                        <path class="st1" d="M-272.9,363.2l35.8,20.7c0.7,0.4,0.7,1.3,0,1.7l-35.8,20.7c-0.7,0.4-1.5-0.1-1.5-0.9V364   C-274.4,363.3-273.5,362.8-272.9,363.2z"/>
                                    </g>
                                    </svg>
                            </div>
                        </a>
                    </div>

            </div>

            <div class="col-lg-6 col-xs-12 py-5 py-lg-1">
                <h3 class="mb-3">Welcome to Reading Teacher Online</h3>
                <p>Reading Teacher Online provides the necessary instruction for students to master the reading basics as quickly as possible.
                    They can then benefit from their formal education and future possibilities.</p>
                <p>Instruction is done via video and online sessions.</p>
                <p>Language is natural, but written language is not. Written language is a skill invented by humans. It has to be taught.</p>
                <p>Until recently, in human history, most children were not taught to read and write.</p>
                <p>Today, even with public education, many children struggle to read and write well enough to cope with the modern world.</p>
                <p>This is an enormous handicap.</p>
            </div>

        </div>
        <div class="row row-margin align-items-center">
            <div class="col-lg-6 col-xs-12 py-5 py-lg-1 order-lg-1">
                <img class="img-fluid rounded img-shadow order-lg-0" src="{% static 'courses_site/girl-reading-book-around-cute-decoration-min.jpg' %}" alt="girl-reading-book-around-cute-decoration-min.jpg">
            </div>
            <div class="col-lg-6 col-xs-12">
                <h3 class="mb-3">Why do so many children struggle to learn to read and write?</h3>
                <p>Many children fail to read and write because they haven't been taught.</p>
                <p>Today, thanks to neuroscience, we have a scientific understanding of reading. We know each child is unique, and each brain is unique.</p>
                <p>We also know that many of our current reading theories do not align with reading research.</p>
                <p>Your child can be taught the fundamentals of the English alphabet system in about twelve hours or less.</p>
                <p>I teach the <a href="{% url 'blog:blog_detail' how_learn_to_read_blog.slug  %}"><b>fundamental reading basics</b></a> step-by-step and provide the graded reading texts, so they get plenty of practice that leads to fluent reading.</p>
            </div>
        </div>
    </div>
    </div>
    <div class="row justify-content-center align-items-center mb-5">
        <div class="col-lg-4 col-xs-12 px-5">
            <h4 class="text-center">I welcome your enquiries. Please contact me at</h4>
            <a href="mailto:marilyn@readingteacheronline.com"><p class="text-center">marilyn@readingteacheronline.com</p></a>
{#            <h5 class="text-center">If you would like to receive our weekly newsletter, please leave your email here.</h5>#}
        </div>
    </div>

    <script>$('#video-gallery').lightGallery({getCaptionFromTitleOrAlt:false, counter:false});</script>

{% endblock %}

templates/course_site/password_reset_confirm.html
{% extends 'base.html' %}
{% block content %}
    <style>

    .password-rule-valid {
        color: #28a745;
    }

    </style>
    <div class="row justify-content-center">
        <div class="col-4">
            {% if validlink %}
                <h3>Reset Password</h3>
                <form method="POST">
                    {% csrf_token %}
                    <label for="id_new_password1">Password:</label>
                    <input type="password" name="new_password1" autocomplete="new-password" required id="id_new_password1" class="form-control">
                    <label for="id_new_password2">Re-enter password:</label>
                    <input type="password" name="new_password2" autocomplete="new-password" required id="id_new_password2" class="form-control">
                    <div class='invalid-feedback'>
                        <p id="password_msg"></p>
                    </div>
                    <small class="form-text text-muted">
                        Your password must contain:
                        <ul>
                            <li id='password-length'>At least 8 characters</li>
                            <li id='password-lowercase'>At least one lowercase letter.</li>
                            <li id='password-uppercase'>At least one uppercase letter</li>
                            <li id='password-digits'>At least one digit</li>
                            <li id='password-special'>At least one special character</li>
                        </ul>
                    </small>
                    <input type="hidden" name="next" value="{{ request.GET.next }}">
                    <button type="submit" onclick="return validation(Event)">
                        Sign Up
                    </button>
                </form>
            {% else %}
                <p class="alert-danger">The password reset link was invalid, possibly because it has already been used. Please request a new password reset</p>
            {% endif %}
        </div>
    </div>


    <script>
    const password1 = document.getElementById('id_new_password1');
	let password_valid = false;
	let digits = false;
	let lower = false;
	let upper = false;
	let special = false;
	let length = false;

	function password_validator(){
	    if (password1.value.match(/[0-9]/g)){
			document.getElementById('password-digits').classList.add('password-rule-valid');
			digits = true;
		}else{
			document.getElementById('password-digits').classList.remove('password-rule-valid');
			digits = false;
		}

		if (password1.value.match(/[a-z]/g)){
			document.getElementById('password-lowercase').classList.add('password-rule-valid');
			lower = true;
		} else {
			document.getElementById('password-lowercase').classList.remove('password-rule-valid');
			lower = false;
		}

		if (password1.value.match(/[A-Z]/g)){
			document.getElementById('password-uppercase').classList.add('password-rule-valid');
			upper = true;
		} else {
			document.getElementById('password-uppercase').classList.remove('password-rule-valid');
			upper = false;
		}

		if (password1.value.match(/[!@#$%^&*()_+\-={}|[\]|\\:";'<>?,./]/g)){
			document.getElementById('password-special').classList.add('password-rule-valid');
			special = true;
		} else {
			document.getElementById('password-special').classList.remove('password-rule-valid');
			special = false;
		}

		if (password1.value.length >= 8){
			document.getElementById('password-length').classList.add('password-rule-valid');
			length = true;
		} else {
			document.getElementById('password-length').classList.remove('password-rule-valid');
			length = false;
		}

		password_valid = digits && lower && upper && special && length;
		if (password_valid){
		    password1.classList.remove('is-invalid');
		    password1.classList.add('is-valid');
        } else {
		    password1.classList.remove('is-valid');
        }
		return password_valid;
    }

	password1.addEventListener('input', password_validator)

    function validation() {
        let valid = true;
        const password1 = document.getElementById('id_new_password1');
        const password2 = document.getElementById('id_new_password2');

        if (password1.value.length === 0) {
            valid = false;
            password1.classList.add('is-invalid');
            document.getElementById("password_msg").innerHTML = "Enter your password";
        } else if (password1.value !== password2.value) {
            valid = false;
            password1.classList.add('is-invalid');
            password2.classList.add('is-invalid');
            document.getElementById("password_msg").innerHTML = "Passwords do not match";
        } else {
            if (password_validator()) {
                password1.classList.remove('is-invalid');
                password1.classList.add('is-valid');
                password2.classList.remove('is-invalid');
                password2.classList.add('is-valid');
                document.getElementById("password_msg").innerHTML = "";
            } else {
                valid = false;
                password1.classList.add('is-invalid');
                password2.classList.add('is-invalid');
                document.getElementById("password_msg").innerHTML = "Password not valid";
            }

        }
        return valid;
    }
    </script>
{% endblock %}

templates/course_site/signupuser.html
{% extends "base.html" %}

{% block content %}

    <style>

    .password-rule-valid {
        color: #28a745;
    }

    </style>

<div class="container">
	<div class="row justify-content-center">
		<p class="h1">Sign up</p>
	</div>
	<div class="row justify-content-center">
		<form method="POST" class="m-2 needs-validation" novalidate>
            {% csrf_token %}
			<div class="row">
				<div class="col-md-6 col-xs-12">
					<div class="form-group">
						<label for="firstname">First Name:</label>
						<input type="text" value="{{ firstname }}" name="firstname" maxlength="150" autocapitalize="none" autocomplete="off" autofocus required id="firstname" class="form-control {{ make_valid }}">
						<div class='invalid-feedback'>
							Enter your first name
						</div>						
					</div>
				</div>
				<div class="col-md-6 col-xs-12">
					<div class="form-group">		
						<label for="lastname">Last Name:</label>
						<input type="text" value="{{ lastname }}" name="lastname" maxlength="150" autocapitalize="none" autocomplete="off" autofocus required id="lastname" class="form-control {{ make_valid }}">
						<div class='invalid-feedback'>
							Enter you last name
						</div>
                    </div>
				</div>
			</div>

			<label for="id_username">Username:</label>
			<input type="text" value="{{ username }}" name="username" maxlength="150" autocapitalize="none" autocomplete="off" autofocus required id="id_username" class="form-control {{ un_is_invalid }}">
			<div class='invalid-feedback'>
				<p id='username_msg'>{{ un_error_msg }}</p>
			</div>


			<label for="email">Email:</label>
			<input type="email" value="{{ email }}" name="email" autocapitalize="none" autocomplete="off" autofocus required id="email" class="form-control {{ make_valid }}">
			<div class='invalid-feedback'>
				<p id='email_msg'></p>
			</div>


			<label for="id_password1">Password:</label> 
			<input type="password" name="password1" autocomplete="new-password" required id="id_password1" class="form-control">
			<label for="id_password2">Re-enter password:</label> 
			<input type="password" name="password2" autocomplete="new-password" required id="id_password2" class="form-control">
			<div class='invalid-feedback'>
				<p id="password_msg"></p>
			</div>
			<small class="form-text text-muted">
				Your password must contain:
				<ul>
                    <li id='password-length'>At least 8 characters</li>
					<li id='password-lowercase'>At least one lowercase letter.</li>
					<li id='password-uppercase'>At least one uppercase letter</li>
					<li id='password-digits'>At least one digit</li>
					<li id='password-special'>At least one special character</li>					
				</ul>
			</small>
            <input type="hidden" name="next" value="{{ request.GET.next }}">
			<button type="submit" onclick="return validation(Event)">
				Sign Up
			</button>

		</form>
	</div>
</div>

<script>
	
	const password1 = document.getElementById('id_password1');
	let password_valid = false;
	let digits = false;
	let lower = false;
	let upper = false;
	let special = false;
	let length = false;

	function password_validator(){
	    if (password1.value.match(/[0-9]/g)){
			document.getElementById('password-digits').classList.add('password-rule-valid');
			digits = true;
		}else{
			document.getElementById('password-digits').classList.remove('password-rule-valid');
			digits = false;
		}

		if (password1.value.match(/[a-z]/g)){
			document.getElementById('password-lowercase').classList.add('password-rule-valid');
			lower = true;
		} else {
			document.getElementById('password-lowercase').classList.remove('password-rule-valid');
			lower = false;
		}

		if (password1.value.match(/[A-Z]/g)){
			document.getElementById('password-uppercase').classList.add('password-rule-valid');
			upper = true;
		} else {
			document.getElementById('password-uppercase').classList.remove('password-rule-valid');
			upper = false;
		}

		if (password1.value.match(/[!@#$%^&*()_+\-={}|[\]|\\:";'<>?,./]/g)){
			document.getElementById('password-special').classList.add('password-rule-valid');
			special = true;
		} else {
			document.getElementById('password-special').classList.remove('password-rule-valid');
			special = false;
		}

		if (password1.value.length >= 8){
			document.getElementById('password-length').classList.add('password-rule-valid');
			length = true;
		} else {
			document.getElementById('password-length').classList.remove('password-rule-valid');
			length = false;
		}

		password_valid = digits && lower && upper && special && length;
		if (password_valid){
		    password1.classList.remove('is-invalid');
		    password1.classList.add('is-valid');
        } else {
		    password1.classList.remove('is-valid');
        }
		return password_valid;
    }

	password1.addEventListener('input', password_validator)


function validation() {
	let valid = true;
	const fname = document.getElementById('firstname');
	const lname = document.getElementById('lastname');
	const username = document.getElementById('id_username');
	const email = document.getElementById('email');
	const password1 = document.getElementById('id_password1');
	const password2 = document.getElementById('id_password2');

	if (!fname.checkValidity()){
		valid = false;
		fname.classList.add('is-invalid');
	}else{
		fname.classList.remove('is-invalid');
		fname.classList.add('is-valid');
	}

	if (!lname.checkValidity()){
		valid = false;
		lname.classList.add('is-invalid');
	}else{
		lname.classList.remove('is-invalid');
		lname.classList.add('is-valid');
	}


	if (username.value.length === 0){
		valid = false;
		username.classList.add('is-invalid');
		document.getElementById("username_msg").innerHTML = "Enter a username";
	} else if (!username.value.match(/[a-zA-Z0-9_]/g)){
		valid = false;
		username.classList.add('is-invalid');
		document.getElementById("username_msg").innerHTML = "Username can only use upper and lowercase letters, digits and underscore.";
	} else if (username.value.match(/[a-zA-Z0-9_]/g).length !== username.value.length){
		valid = false;
		username.classList.add('is-invalid');
		document.getElementById("username_msg").innerHTML = "Username can only use upper and lowercase letters, digits and underscore.";
	}else{
		username.classList.remove('is-invalid');
		username.classList.add('is-valid');
	}
	

	if (email.value.length === 0){
		valid = false;
		email.classList.add('is-invalid');
		document.getElementById("email_msg").innerHTML = "Enter your email";
	} else if (!email.value.match(/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/)){
		valid = false;
		email.classList.add('is-invalid');
		document.getElementById("email_msg").innerHTML = "Enter a valid email address";		
	} else {
		email.classList.remove('is-invalid');
		email.classList.add('is-valid');
		document.getElementById("email_msg").innerHTML = "";		

	}

	if (password1.value.length === 0){
		valid = false;
		password1.classList.add('is-invalid');
		document.getElementById("password_msg").innerHTML = "Enter your password";
	}else if (password1.value !== password2.value){
		valid = false;
		password1.classList.add('is-invalid');
		password2.classList.add('is-invalid');		
		document.getElementById("password_msg").innerHTML = "Passwords do not match";
	} else {
	    if (password_validator()){
            password1.classList.remove('is-invalid');
		    password1.classList.add('is-valid');
		    password2.classList.remove('is-invalid');
		    password2.classList.add('is-valid');
		    document.getElementById("password_msg").innerHTML = "";
        } else {
            valid = false;
		    password1.classList.add('is-invalid');
		    password2.classList.add('is-invalid');
		    document.getElementById("password_msg").innerHTML = "Password not valid";
        }

	}
	return valid;
}
</script>

{% endblock %}