blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.allBlogs, name='allBlogs'),
    path('<str:slug>/', views.detail, name='blog_detail'),
]

memberships/urls.py
from django.urls import path
from . import views

app_name = 'memberships'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('settings/', views.settings, name='settings'),
    path('success/', views.payment_success, name='payment_success'),
    path('updatesuccess', views.update_success, name='update_success'),
    path('webhook/', views.my_webhook, name='my_webhook'),
    path('join/', views.join, name='join'),
    path('cancel/', views.cancel_subscription, name='cancel_subscription'),

]

readingTeacherOnline/urls.py
from django.contrib import admin
from django.urls import path, include
from courses_site import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('signup/', views.signupuser, name='signupuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('login/', views.loginuser, name='loginuser'),
    path('blog/', include('blog.urls')),
    path('courses/', views.all_courses, name='all_courses'),
    path('courses/<str:slug>/', views.course_detail, name='course_detail'),
    path('courses/<str:slug>/<int:order_number>', views.course_video, name='course_video'),
    path('ckeditor', include('ckeditor_uploader.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('memberships/', include('memberships.urls')),
    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="auth/password_reset.html", email_template_name='password_reset_email.html'),
         name="reset_password"),
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="auth/password_reset_sent.html"),
         name="password_reset_done"),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='auth/password_reset_confirm.html'),
         name="password_reset_confirm"),
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='auth/password_reset_done.html'),
         name="password_reset_complete"),
    path('change_password/',
         auth_views.PasswordChangeView.as_view(template_name='auth/change_password.html'),
         name='change_password'),
    path('activation_email_sent', views.activation_email_sent, name='activation_email_sent'),
    path('account_activated', views.account_activated, name='account_activation_complete'),
    path('activate/<uidb64>/<token>/', views.activate_account, name='activate'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'courses_site.views.error_404'

memberships/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    stripe_id = models.CharField(max_length=255)
    subscription_id = models.CharField(max_length=255, default='')
    cancel_at_period_end = models.BooleanField(default=False)
    current_period_end = models.DateTimeField()

    class Meta:
        verbose_name_plural = 'customers'

    def __str__(self):
        return self.user.email


class Coupons(models.Model):
    code = models.CharField(max_length=10)
    percent_off = models.IntegerField()
    durations = (
        (0, 'once'),
        (1, 'repeating'),
        (2, 'forever')
    )
    duration = models.IntegerField(choices=durations, default=0)
    duration_months = models.IntegerField(default=0, blank=True, null=True)

    class Meta:
        verbose_name_plural = 'coupons'

    def __str__(self):
        return self.code


class CancelSurvey(models.Model):
    satisfaction_choices = (
        (0, 'Very Satisfied'),
        (1, 'Satisfied'),
        (2, 'Neutral'),
        (3, 'Unsatisfied'),
        (4, 'Very Unsatisfied'),
    )
    satisfaction = models.IntegerField(choices=satisfaction_choices)

    reasons = (
        (0, "No longer needed it"),
        (1, "It didn't meet my needs"),
        (2, "Found an alternative"),
        (3, "Quality was less than expected"),
        (4, "Ease of use was less than expected"),
        (5, "Access to the service was less than expected"),
        (6, "Customer service was less than expected"),
        (7, "Other")
    )
    primary_reason = models.IntegerField(choices=reasons)
    other = models.TextField(null=True)
    suggestion = models.TextField(null=True)

memberships/views.py
from django.shortcuts import render, redirect
from .models import Coupons, Customer, CancelSurvey
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import stripe
from django.conf import settings
from django.http import HttpResponse
from django.views.decorators.http import require_GET
from datetime import datetime, timedelta
from django.utils import timezone
from django.urls import reverse

stripe.api_key = settings.STRIPE_SECRET_KEY
STRIPE_PUBLIC_KEY = settings.STRIPE_PUBLIC_KEY
STRIPE_PRICE_ID = settings.STRIPE_PRICE_ID
STRIPE_PRODUCT_ID = settings.STRIPE_PRODUCT_ID

endpoint_secret = settings.STRIPE_WEBHOOK_ENDPOINT_SECRET

@csrf_exempt
def my_webhook(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, endpoint_secret
        )
    except ValueError as e:
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        return HttpResponse(status=400)

    if event['type'] == 'checkout.session.completed':
        session = event['data']['object']
        if session['mode'] == 'setup':
            setup_intent = session['setup_intent']
            intent = stripe.SetupIntent.retrieve(setup_intent)
            customer = intent['customer']
            payment_method = intent['payment_method']

            # update customer's payment method
            stripe.Customer.modify(
                customer,
                invoice_settings={'default_payment_method': payment_method}
            )
            return HttpResponse(status=200)

        elif session['mode'] == 'subscription':
            # try to retrieve a customer object for user or create a new one
            try:
                customer = Customer.objects.get(user=session['client_reference_id'])
            except Customer.DoesNotExist:
                customer = Customer()
                customer.user_id = session['client_reference_id']
            customer.stripe_id = session['customer']
            subscription_id = session['subscription']
            subscription_response = stripe.Subscription.retrieve(subscription_id)
            customer.cancel_at_period_end = True if subscription_response['cancel_at_period_end'] == 'true' else False
            current_period_end_datetime = datetime.fromtimestamp(subscription_response['current_period_end']) + timedelta(days=7)  # add 7 days grace after potential failed payment
            customer.current_period_end = current_period_end_datetime
            customer.subscription_id = subscription_id
            customer.save()

    # if payment is successful, update current_period_end for customer
    elif event['type'] == 'payment_intent.succeeded':
        event_object = event['data']['object']
        try:
            customer = Customer.objects.get(stripe_id=event_object['customer'])
            subscription_id = customer.subscription_id
            subscription_response = stripe.Subscription.retrieve(subscription_id)
            customer.current_period_end = datetime.fromtimestamp(subscription_response['current_period_end']) + timedelta(days=7)  # add 7 days grace after potential failed payment
            customer.save()
        except Customer.DoesNotExist:
            print('No Customer')
            return HttpResponse(status=200)

    elif event['type'] == 'payment_intent.payment_failed':
        event_object = event['data']['object']
        try:
            # get customer object
            customer = Customer.objects.get(stripe_id=event_object['customer'])
        except Customer.DoesNotExist:
            # not a current customer so no action required yet (probably failed at checkout)
            return HttpResponse(status=200)

        print(f'Customer: {customer.user}\nPayment Failed\nLetting Support know.....')

    # elif event['type'] == 'customer.subscription.deleted':
    #     print(event)
    #     event_object = event['data']['object']
    #     subscription_id = event_object['id']
    #     subscription = Subscriptions.objects.get(stripe_subscription_id=subscription_id)
    #     subscription.current = False

    return HttpResponse(status=200)


def join(request):
    retrieved_stripe_price = stripe.Price.retrieve(STRIPE_PRICE_ID)
    price = int(retrieved_stripe_price['unit_amount']/100)
    return render(request, 'memberships/join.html', {'price': price})


@login_required(login_url='/login/')
@ require_GET
def checkout(request):
    if request.user.is_superuser:
        return redirect('home')
    try:
        if request.user.customer.current_period_end > timezone.now():
            return redirect('memberships:settings')

    except Customer.DoesNotExist:
        pass


    # get all coupons stored in db
    coupons = Coupons.objects.all()
    coupons_dict = {coupon.code: coupon.percent_off for coupon in coupons}

    # set initial prices and totals
    coupon = 'none'
    retrieved_stripe_price = stripe.Price.retrieve(STRIPE_PRICE_ID)
    price = int(retrieved_stripe_price['unit_amount'])
    og_dollar = price/100
    coupon_dollar = 0
    product_name = stripe.Product.retrieve(STRIPE_PRODUCT_ID)['name']

    product_period = ''

    product_recurring_period = retrieved_stripe_price['recurring']['interval']
    if product_recurring_period == 'day':
        product_period = 'Daily Membership'
    elif product_recurring_period == 'week':
        product_period = 'Weekly Membership'
    elif product_recurring_period == 'month':
        product_period = 'Monthly Membership'
    elif product_recurring_period == 'year':
        product_period = 'Yearly Membership'


    currency = retrieved_stripe_price['currency'].upper()

    # initial session parameters
    payment_method_types = ['card']
    line_items = [{
        'price': STRIPE_PRICE_ID,
        'quantity': 1,
    }]
    mode = 'subscription'
    client_reference_id = request.user.id
    customer_email = request.user.email
    customer = None
    subscription_data = None

    # check if user has a stripe customer id already and add that to the session
    try:
        stripe_customer_id = Customer.objects.get(user=request.user.id).stripe_id
        customer = stripe_customer_id
        customer_email = None
    except Customer.DoesNotExist:
        pass

    # check if coupon was added
    if 'coupon' in request.GET and request.GET['coupon'].upper() in coupons_dict:
        coupon = request.GET['coupon'].upper()
        percentage = coupons_dict[coupon]

        # create coupon or skip if it already exists
        try:
            stripe.Coupon.create(
                percent_off=percentage,
                duration='once',
                id=coupon,
            )
        except:
            pass

        # add coupon to session
        subscription_data = {
            'coupon': coupon
        }

        # set new prices and totals
        coupon_price = int((percentage / 100) * price)
        price = price - coupon_price
        coupon_dollar = str(coupon_price)[:-2] + "." + str(coupon_price)[-2:]
        final_dollar = str(price)[:-2] + "." + str(price)[-2:]
    else:
        # set new prices and totals
        og_dollar = str(og_dollar)[:-2] + "." + str(price)[-2:]
        final_dollar = str(price)[:-2] + "." + str(price)[-2:]

    # create session
    session = stripe.checkout.Session.create(
        payment_method_types=payment_method_types,
        line_items=line_items,
        mode=mode,
        success_url=f'{request.scheme}://{request.get_host()}{reverse("memberships:payment_success")}',
        cancel_url=f'{request.scheme}://{request.get_host()}{reverse("memberships:checkout")}',
        client_reference_id=client_reference_id,
        customer_email=customer_email,
        customer=customer,
        subscription_data=subscription_data

    )

    return render(request, 'memberships/checkout.html',
                  {'coupon': coupon,
                   'price': price,
                   'og_dollar': og_dollar,
                   'coupon_dollar': coupon_dollar,
                   'final_dollar': final_dollar,
                   'session': session,
                   'product_name': product_name,
                   'product_period': product_period,
                   'currency': currency,
                   'stripe_public_key': STRIPE_PUBLIC_KEY})


@login_required(login_url='/login/')
def settings(request):
    cancel_at_period_end = False
    try:
        customer = request.user.customer.stripe_id
        session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            mode='setup',
            customer=customer,
            success_url=f'{request.scheme}://{request.get_host()}{reverse("memberships:payment_success")}',
            cancel_url=f'{request.scheme}://{request.get_host()}{reverse("memberships:settings")}',
        )
        member_until = request.user.customer.current_period_end
        cancel_at_period_end = True if request.user.customer.cancel_at_period_end else False
    except Customer.DoesNotExist:
        session = None
        member_until = False
    date_joined = request.user.date_joined
    return render(request, 'memberships/settings.html',
                  {'session': session,
                   'date_joined': date_joined,
                   'member_until': member_until,
                   'cancel_at_end_period': cancel_at_period_end,
                   'stripe_public_key': STRIPE_PUBLIC_KEY})


@login_required(login_url='/login/')
def payment_success(request):
    return render(request, 'memberships/payment_success.html')


@login_required(login_url='/login/')
def payment_cancel(request):
    return render(request, 'memberships/payment_cancel.html')


def update_success(request):
    return render(request, 'memberships/update_success.html')


@login_required(login_url='/login/')
def cancel_subscription(request):

templates/memberships/cancel_survey.html
{% extends 'base.html' %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-6 col-xs-12 mx-4">
            <h2 class="my-5 border-bottom text-center">Tell us why you are leaving.</h2>
            <form action="{% url 'memberships:cancel_subscription' %}" method="POST" id="survey">
                {% csrf_token %}
                    <div>
                    <h5 class="my-4 font-weight-bold">Overall, how satisfied were you with Reading Teacher Online?</h5>
                        <div id="satisfaction-message" class='text-danger' style="display: none">
                            <div class="row">
                                <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-exclamation-circle mr-3" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                  <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                  <path d="M7.002 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 4.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 4.995z"/>
                                </svg>
                                <p>Please choose a satisfaction level</p>
                            </div>
                        </div>
                        {% for satisfaction_choice in satisfaction_choices %}
                            <div class="form-check ml-5">
                                  <input class="form-check-input"
                                         type="radio"
                                         name="satisfaction"
                                         id="satisfaction{{ forloop.counter0 }}"
                                         value="{{ forloop.counter0 }}">
                                  <label class="form-check-label" for="satisfaction{{ forloop.counter0 }}">
                                    {{ satisfaction_choice }}
                                  </label>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="my-3 border-top">
                    <h5 class="my-4 font-weight-bold">What was the primary reason for cancelling your membership?</h5>
                        <div id="reason-message" class='text-danger' style="display: none">
                            <div class="row">
                                <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-exclamation-circle mr-3" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                  <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                  <path d="M7.002 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 4.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 4.995z"/>
                                </svg>
                                <p>Please choose a reason</p>
                            </div>
                        </div>
                        {% for reason in reasons %}
                            <div class="form-check ml-5">
                                  <input class="form-check-input"
                                         type="radio"
                                         name="reason"
                                         id="reason{{ forloop.counter0 }}"
                                         value="{{ forloop.counter0 }}">
                                  <label class="form-check-label" for="reason{{ forloop.counter0 }}">
                                    {{ reason }}
                                  </label>
                            </div>
                        {% endfor %}
                    </div>
                  <div class="form-group">
                      <svg  id="other-reason-svg" width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-exclamation-circle mr-3 text-danger" fill="currentColor" xmlns="http://www.w3.org/2000/svg" style="display: none">
                          <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                          <path d="M7.002 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 4.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 4.995z"/>
                      </svg>
                        <label id="other-reason-label" class="font-weight-bold" for="other_reason">If other, please specify:</label>
                        <textarea class="form-control" id="other_reason" name="other_reason" rows="2"></textarea>
                  </div>

                <div class="form-group">
                    <label class="font-weight-bold" for="suggestion">What could we do to improve Reading Teacher Online?</label>
                    <textarea class="form-control" id="suggestion" name="suggestion" rows="4"></textarea>
                  </div>
                <button type="submit" class="btn btn-danger btn-block my-5" id="cancel-button" onclick="return validation(Event)">Cancel Membership</button>
            </form>
        </div>
    </div>
    <script>


    function validation() {

        let valid = true;
        let reason_message = document.getElementById('reason-message');
        let satisfaction_message = document.getElementById('satisfaction-message');


        try {
            let reason = document.querySelector('input[name="reason"]:checked').value;
            reason_message.style.display = 'none';
            console.log(typeof(reason));
            if (reason === '7') {
                let other = document.getElementById('other_reason');
                console.log(other.value.length);
                if (other.value.length === 0) {
                    let other_reason_svg = document.getElementById('other-reason-svg');
                    other_reason_svg.style.display = 'block';
                    other_reason_svg.classList.add('d-inline')
                    let other_reason_label = document.getElementById('other-reason-label');
                    other_reason_label.classList.add('text-danger');
                    valid = false;
                }
            } else {
                let other_reason_svg = document.getElementById('other-reason-svg');
                other_reason_svg.style.display = 'none';
                other_reason_svg.classList.remove('d-inline')
                let other_reason_label = document.getElementById('other-reason-label');
                other_reason_label.classList.remove('text-danger');
            }
        }
        catch (err){
                reason_message.style.display = 'block';
                valid = false;
            }

        try {
            let satisfaction = document.querySelector('input[name="satisfaction"]:checked').value;
            satisfaction_message.style.display = 'none';
        }
        catch (err){
                satisfaction_message.style.display = 'block';
                valid = false;
            }

        if (!valid){
            window.scrollTo(0,0);
        }

        return valid;

    }






    </script>
{% endblock %}

templates/memberships/checkout.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="row justify-content-center mt-5">
      <div class="col-md-4 order-md-2 mb-4">
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-muted">Your cart</span>
          <span class="badge badge-secondary badge-pill">1</span>
        </h4>
        <ul class="list-group mb-3">
          <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
              <h6 class="my-0">{{ product_name }}</h6>
              <small class="text-muted">{{ product_period }}</small>
            </div>
            <span class="text-muted">${{ og_dollar }}</span>
          </li>
          {% if coupon != 'none' %}
          <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
              <h6 class="my-0">Promo code</h6>
              <small>{{ coupon|upper }}</small>
            </div>
            <span class="text-success">-${{ coupon_dollar }}</span>
          </li>
          {% endif %}
          <li class="list-group-item d-flex justify-content-between">
            <span>Total ({{ currency }})</span>
            <strong>${{ final_dollar }}</strong>
          </li>
        </ul>

        <form class="card p-2" action="{% url 'memberships:checkout' %}" method="GET">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Promo code" name="coupon">
            <div class="input-group-append">
              <button type="submit" class="btn btn-secondary">Redeem</button>
            </div>
          </div>
        </form>
        <div class="row justify-content-center my-3">
            <button type="submit" class="btn btn-primary" id="checkout-button">Proceed to Checkout</button>
        </div>
        <div class="text-center pt-3">
            <script src="https://js.stripe.com/v3/"></script>

            <script>
                var stripe = Stripe('{{ stripe_public_key }}');

                var checkoutButton = document.getElementById('checkout-button');

                checkoutButton.addEventListener('click', function() {
                  stripe.redirectToCheckout({
                    sessionId: '{{ session.id }}'
                  }).then(function (result) {
                  });
                });
            </script>
        </div>
      </div>
  </div>
</div>

{% endblock %}

templates/memberships/join.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
              <h1 class="display-4">Premium Membership</h1>
              <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam mattis ligula ac iaculis ultrices.
                  Nulla sodales, massa in semper ornare, leo magna varius eros, non ullamcorper erat urna non neque. Cras auctor
                  mauris massa, et tincidunt odio rhoncus eget. Integer porttitor, magna tincidunt pulvinar ornare, massa ante
                  eleifend nunc, at.
              </p>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6 col-xs-12">
                <div class="card-deck mb-3 text-center">
                    <div class="card mb-4 shadow-sm">
                      <div class="card-header">
                        <h4 class="my-0 font-weight-normal">Monthly</h4>
                      </div>
                      <div class="card-body">
                        <h1 class="card-title pricing-card-title">${{ price }} <small class="text-muted">/ mo</small></h1>
                        <ul class="list-unstyled mt-3 mb-4">
                          <li>Nullam eu dapibus</li>
                          <li> Phasellus molestie vulputate</li>
                          <li>Donec quis porttitor</li>
                          <li>Sed congue ultrices</li>
                        </ul>
                        <a href="{% url 'memberships:checkout' %}"><button type="button" class="btn btn-lg btn-block btn-outline-primary">Get started</button></a>
                      </div>
                    </div>
                </div>
            </div>
        </div>

        </div>
{% endblock %}

templates/memberships/payment_cancel.html
{% extends 'base.html' %}

{% block content %}

    <p>There was an issue with the payment</p>

{% endblock %}

templates/memberships/payment_success.html
{% extends 'base.html' %}

{% block content %}

    <div class="row justify-content-center mt-5">
        <div class="col-8 col-md-4">
            <p class="alert-success text-center">Membership has been successfully created. You now have access to premium content.</p>
        </div>
    </div>

{% endblock %}

templates/memberships/settings.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-5">
    <div class="row justify-content-center">
    <div class="col-md-6 col-xs-12 m-2">
    <h1 class="mb-5 pb-3 border-bottom text-center">Account Settings</h1>

    <div class="row">
        <div class="col">
            <p class="text-left">Account Created:</p>
        </div>
        <div class="col">
             <p class="text-right">{{ date_joined| date:"d M Y" }}</p>
        </div>
    </div>

    {% if session %}
        <div class="row">
            <div class="col">
                <p class="text-left">Premium Access Till:</p>
            </div>
            <div class="col">
                 <p class="text-right">{{ member_until| date:"d M Y" }}</p>
            </div>
        </div>
    {% endif %}

    <a href="{% url 'change_password' %}" class="btn btn-primary btn-block my-2">Reset Password</a>

    {% if session %}
        <div>
        <button type="submit" class="btn btn-primary my-2 btn-block" id="update-button">Update Payment Details</button>

            <div class="text-center">
                <script src="https://js.stripe.com/v3/"></script>

                <script>
                    var stripe = Stripe('{{ stripe_public_key }}');

                    var checkoutButton = document.getElementById('update-button');

                    checkoutButton.addEventListener('click', function() {
                      stripe.redirectToCheckout({
                        sessionId: '{{ session.id }}'
                      }).then(function (result) {
                        // If `redirectToCheckout` fails due to a browser or network
                        // e                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          rror, display the localized error message to your customer
                        // using `result.error.message`.

                      });
                    });
                </script>
            </div>
    {% endif %}


    {% if session %}
        {% if not cancel_at_end_period %}
                <a href="{% url 'memberships:cancel_subscription' %}" class="btn btn-danger my-2 btn-block" id="cancel-button">Cancel Membership</a>
        {% else %}
            <p class="alert- py-2 my-3 text-center">You have cancelled your membership and will end on {{ member_until| date:"d M Y" }}</p>
        {% endif %}
        </div>
    {% endif %}


    </div>
    </div>
</div>
{% endblock %}

templates/memberships/update_success.html
{% extends 'base.html' %}
{% block content %}

    <p>Your payment details have been successfully updated</p>

{% endblock %}